[theme]
primaryColor = "#0F52BA"    # Azul Zafiro (Profesional y Serio)
backgroundColor = "#FFFFFF" # Fondo Blanco Limpio
secondaryBackgroundColor = "#F0F2F6" # Gris muy suave para el menú lateral
textColor = "#262730"       # Gris oscuro (casi negro) para lectura cómoda
font = "sans serif"         # Tipografía estándar moderna (tipo Arial/Roboto)

[server]
runOnSave = true
